repository:
  name: uk-mobile
  description: uk-mobile
  homepage: https://www.camelotls.com
  private: true
  has_issues: false
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
# TODO: Set UK Codeshare outside-collaborators 
# https://jira.camelot.global/browse/PLAT-5098
#collaborators: []
teams:
  - name: everyone
    permission: push
  - name: appletizers
    permission: maintain
  - name: gangsterappers
    permission: maintain
branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions:
        apps: []
        users: []
        teams: []
