name: "Jira ticket creation"
description: "Creates a Jira ticket base on the input of a previous action"
inputs:
    JIRA_USER:
        description: "Github secret for the JIRA user email for external access"
        required: true
    JIRA_PASSWORD:
        description: "Github secret for the JIRA API token for external access"
        required: true
    JIRA_PROJECT:
        description: "The project key for Jira"
        required: true
    JIRA_URI:
        description: "The Jira URI used for the REST API to make the requests to"
        required: true
    INPUT_JSON:
        description: "The JSON input to be parsed"
        required: true
    REPORT_INPUT_KEYS:
        description: "A list of keys of the input JSON you provide that will be parsed and included in the report"
        required: true
    IS_NPM_AUDIT:
        description: "Indicates if the JSON to be used for the JIRA REST calls is based on npm audit since there is a need for special treating of the overview report field"
        required: false
    JIRA_ISSUE_TYPE:
        description: "The type of the issue to be used whuile searching for existing issues. This is needed in order to avoid duplicating already raised issues"
        required: false
        default: "Security Vulnerability"
    RUNS_ON_GITHUB:
        description: "Indicates if the action runs on GitHub or locally, on a Docker container, for testing purporses"
        required: true
        default: true
runs:
    using: "docker"
    image: "Dockerfile"
