FROM node:20

WORKDIR /

ARG JIRA_ON_CLOUD
ARG JIRA_CLOUD_TOKEN
ARG JIRA_USER
ARG JIRA_PASSWORD
ARG JIRA_PROJECT
ARG JIRA_URI
ARG INPUT_JSON
ARG REPORT_INPUT_KEYS
ARG ISSUE_TYPE
ARG RUNS_ON_GITHUB

ENV JIRA_ON_CLOUD=$JIRA_ON_CLOUD \
    JIRA_CLOUD_TOKEN=$JIRA_CLOUD_TOKEN \
    JIRA_USER=$JIRA_USER \
    JIRA_PASSWORD=$JIRA_PASSWORD \
    JIRA_PROJECT=$JIRA_PROJECT \
    JIRA_URI=$JIRA_URI \
    INPUT_JSON=$INPUT_JSON \
    REPORT_INPUT_KEYS=$REPORT_INPUT_KEYS \
    ISSUE_TYPE=$ISSUE_TYPE \
    RUNS_ON_GITHUB=$RUNS_ON_GITHUB

COPY index.js package.json pnpm-lock.yaml ./
COPY config/ ./config
COPY helpers/ ./helpers
COPY utils/ ./utils

RUN npm i -g pnpm@9.6.0

RUN pnpm install

ENTRYPOINT ["node", "/index.js"]
