FROM node:12.9.0

WORKDIR /

ARG JIRA_USER
ARG JIRA_PASSWORD
ARG JIRA_PROJECT
ARG JIRA_URI
ARG INPUT_JSON
ARG REPORT_INPUT_KEYS
ARG ISSUE_TYPE
ARG RUNS_ON_GITHUB

ENV JIRA_USER=$JIRA_USER \
    JIRA_PASSWORD=$JIRA_PASSWORD \
    JIRA_PROJECT=$JIRA_PROJECT \
    JIRA_URI=$JIRA_URI \
    INPUT_JSON=$INPUT_JSON \
    REPORT_INPUT_KEYS=$REPORT_INPUT_KEYS \
    ISSUE_TYPE=$ISSUE_TYPE \
    RUNS_ON_GITHUB=$RUNS_ON_GITHUB

COPY index.js package.json package-lock.json ./
COPY config/ ./config
COPY helpers/ ./helpers
COPY utils/ ./utils

RUN npm install

ENTRYPOINT ["node", "/index.js"]
