name: Git Linter

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Git Linter

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install gitlint
        run: pip install gitlint
      - name: Execute gitlint
        run: gitlint --config=.github/config/gitlint/gitlint.cfg --debug